DESCRIPTION = " stx-integ-config-files"

require config-files/audit-config.inc
require config-files/io-scheduler.inc
require config-files/docker-config.inc
require config-files/iptables-config.inc
require config-files/memcached-custom.inc
require config-files/ntp-config.inc
require config-files/pam-config.inc
require config-files/shadow-utils-config.inc
require config-files/rsync-config.inc
require config-files/sudo-config.inc
require config-files/syslog-ng-config.inc
require config-files/util-linux-config.inc
